# Generated by Django 4.1.4 on 2022-12-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myown',
            fields=[
                ('U_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Desc', models.CharField(max_length=200)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
