# Generated by Django 4.0.5 on 2022-12-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapp', '0002_user_blog_delete_myown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_blog',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
