# Generated by Django 4.0.5 on 2022-12-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapp', '0003_alter_user_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_blog',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
