# Generated by Django 4.0.5 on 2022-12-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapp', '0005_alter_user_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_blog',
            name='Desc',
            field=models.CharField(max_length=2000),
        ),
    ]
